export const mainBookSlider = [
	{
		id: 1,
		category: '소설 추천',
		title: '현대 미국',
		title2: '단편문학의 정수',
		content: '가슴이 저미고 마음에 흔적을 남기는 이야기들',
		img: '/main/thedisappeared.jpg',
		background: '#F2CAC8',
	},
	{
		id: 2,
		category: '인문학 추천',
		title: '공간-권력에 대한',
		title2: '푸코의 사유의 궤적',
		content: '모든 장소에 맞서는, 절대적으로 다른 공간',
		img: '/main/pouvoiretespace.jpg',
		background: '#C2BFDC',
	},
	{
		id: 3,
		category: '소설 추천',
		title: 'SF 사상 가장 많이',
		title2: '팔린 소설',
		content: '듄 마니아들의 보물창고가 될 만하다.',
		img: '/main/dune.jpg',
		background: '#F4AE25',
	},
	{
		id: 4,
		category: '자기계발 추천',
		title: '최고만을 압축해놓은',
		title2: '루틴',
		content: '성공하는 삶은 저 멀리 있는것이 아니다.',
		img: '/main/miraclemorning.jpg',
		background: '#00A2EA',
	},
	{
		id: 5,
		category: '에세이 추천',
		title: '유품정리사가 써 내려간',
		title2: '떠난 이들의 뒷모습',
		content: '시간의 멈춘 방에서 사람의 의미를 생각하다',
		img: '/main/leftatthememorial.jpg',
		background: '#B4B9D7',
	},
	{
		id: 6,
		category: '과학 추천',
		title: 'KAIST 뇌과학자',
		title2: '김대식 교수 추천',
		content: '미래 100대 기술 주역 선정',
		img: '/main/neurallink.jpg',
		background: '#D0A325',
	},
];
