export const testdatalist = [
	{
		id: 1,
		user: '박캄보',
		title: '베르베르 읽은 사람 모여라',
		content:
			'베르베르는 정말 천재적이다. 그는 프랑스인이며 한국을 너무 사랑한다. 나도 그의 책을 너무나 사랑하는 사람 중 하나이다. 그는 영원했으면 좋겠다.',
		time: '53분전',
		view: 20,
		like: 50,
		comments: 2,
		orderlist: [
			{
				date: '2024-01-11',
				title: '베르베르씨, 오늘은 뭘 쓰세요?',
				author: '베르베르',
				translator: '전미화',
				originprice: 20000,
				saleprice: 18000,
				quantity: 1,
				totalprice: 36000,
			},
		],
	},
	{
		id: 2,
		user: '김원준',
		title: '원더책 아시나요',
		content:
			'원더원더원더더덛ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ',
		time: '1분전',
		view: 10,
		like: 10,
		comments: 4,
		orderlist: [
			{
				date: '2024-01-11',
				title: '베르베르씨, 오늘은 뭘 쓰세요?',
				author: '베르베르',
				translator: '전미화',
				originprice: 20000,
				saleprice: 18000,
				quantity: 1,
				totalprice: 36000,
			},
		],
	},
	{
		id: 3,
		user: '배성완',
		title: '문상훈은 정말 천재다',
		content:
			'문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈문상훈',
		time: '1시간',
		view: 10,
		like: 10,
		comments: 10,
		orderlist: [
			{
				date: '2024-01-11',
				title: '베르베르씨, 오늘은 뭘 쓰세요?',
				author: '베르베르',
				translator: '전미화',
				originprice: 20000,
				saleprice: 18000,
				quantity: 1,
				totalprice: 36000,
			},
		],
	},
	{
		id: 4,
		user: '박캄보',
		title: '베르베르 읽은 사람 모여라',
		content:
			'베르베르는 정말 천재적이다. 그는 프랑스인이며 한국을 너무 사랑한다. 나도 그의 책을 너무나 사랑하는 사람 중 하나이다. 그는 영원했으면 좋겠다.',
		time: '53분전',
		view: 20,
		like: 50,
		comments: 2,
		orderlist: [
			{
				date: '2024-01-11',
				title: '베르베르씨, 오늘은 뭘 쓰세요?',
				author: '베르베르',
				translator: '전미화',
				originprice: 20000,
				saleprice: 18000,
				quantity: 1,
				totalprice: 36000,
			},
		],
	},
	{
		id: 5,
		user: '박캄보',
		title: '베르베르 읽은 사람 모여라',
		content:
			'베르베르는 정말 천재적이다. 그는 프랑스인이며 한국을 너무 사랑한다. 나도 그의 책을 너무나 사랑하는 사람 중 하나이다. 그는 영원했으면 좋겠다.',
		time: '53분전',
		view: 20,
		like: 50,
		comments: 2,
		orderlist: [
			{
				date: '2024-01-11',
				title: '베르베르씨, 오늘은 뭘 쓰세요?',
				author: '베르베르',
				translator: '전미화',
				originprice: 20000,
				saleprice: 18000,
				quantity: 1,
				totalprice: 36000,
			},
		],
	},
];
